### PR TITLE
LocationService API

### PR DESCRIPTION
**Pull request by sjrahn**
This API accepts any well-formed GeoJson within a FeatureCollection. Features are split into their own records in the database and can be queried directly by their autogenerated id number. Individual features can be queried via a Lat/Long coordinate and distance, wherein the closest feature is returned.

API queryable via curl at: https://geoservice.rahn.tech/api/Location
OpenAPI documentation is available at: https://geoservice.rahn.tech/swagger/index.html

### Design Considerations
- Use minimal API for lowest overhead
- Use SQL Server backend to utilize spatial functions (for distance calculation)
- Store GeoJson for fast querying on Get
- Use existing third party libraries where possible

### Out of scope - Future considerations
- Accept features that aren't contained in a FeatureCollection
- Use proper projection and EPSG normalization
- Sanity checks/user feedback on Lat/Long inputs
- Better error handling wrt bad requests
- Unit testing and further refactoring
- API documentation
- Units (requires projection normalization to be accurate)
- Security / Access limitations
- Spatial indexes / tuning
- etc

### CODE REVIEW

**Comment by ckapatch** [comment]
Thanks Steven for this! It is well put together and achieves the ask of the assignment. The solution is nice and concise, I really like how you've identified items that I didn't ask for but would be great for future considerations. Really easy to read, no hoop jumping or extra questions required for understanding. Really well done!

It is obvious by this implementation that you are much more familiar and have more expertise in geodata than I do, the fact that you were able to use external resources & then leverage those tools for finding  the distance is fantastic.

A few comments (not criticism at all), just open discussions:

- Did you tend to in your past to build out the sql scripts for deployment? Have you ever used EF (Core) Migrations? Any reasoning to why you haven't used them or don't use them?
-  Any particular reason to use SQL functions directly instead of using the built in EF core functions for distance queries: https://learn.microsoft.com/en-us/ef/core/modeling/spatial
- The only reason I ask for the above is that we tend to stay away from direct SQL manipulation, not that I view it as evil or incorrect, only more to maintain and additional break points. I'm interested to hearing your take on this.

Again thank you for this coding exercise. I will follow up with the Levvel team today and look forward to speaking with you again soon.

Chad

**Review by ckapatch — APPROVED** [review]
Excellent implementation!

**Comment by sjrahn** [comment]
> Did you tend to in your past to build out the sql scripts for deployment? Have you ever used EF (Core) Migrations? Any reasoning to why you haven't used them or don't use them?

Yes, the vast majority of the sql scripts I have used for deployment and migrations have been done by hand. I know then many pain points involved and would rather use the built-in tools when possible. I'm not sure the exact reasons, but there were some limitations with processes that prevented its use at the time for us. In the case of this exercise, it was just the easiest way for me to accomplish the goal.

> Any particular reason to use SQL functions directly instead of using the built in EF core functions for distance queries: https://learn.microsoft.com/en-us/ef/core/modeling/spatial

TBH I think I forgot that those spatial function were even exposed. I was used to doing a lot of this directly in SQL and it just felt natural to do it this way from my experience. But you are correct it's way better to use the Distance method for a multitude of reasons. I just profiled it and it translated into basically the exact same function I had written anyway, just without all the overhead of need to create the function, convert the sql params, and have the disconnect between C# and TSQL in implementation of logic. It's also more testable this way and you can properly utilize deferred execution of LINQ!

> The only reason I ask for the above is that we tend to stay away from direct SQL manipulation, not that I view it as evil or incorrect, only more to maintain and additional break points. I'm interested to hearing your take on this.

Oh absolutely, I avoid it as much as possible. My main concern was making sure that the calculation was not being done by the microservice itself since it should be acting solely (at least in this case) as an interpreter between the user and the data warehouse. There may inevitably some situations where there is no appropriate way to express what you want the data warehouse to do in the code, or it may just not be efficient at all and may necessitate direct intervention. I would agree that it should be a last resort because the maintainability drops as soon as you make that disconnect. I think the extent of it should be exposing your own sql server functions or stored procedures, like what I did to keep it clean and concise. I've dealt with raw sql query calls from code before and it's a nightmare.

Thanks for the feedback and I look forward to hearing to speaking soon as well!

**Comment by ckapatch** [comment]
Hey Steven, I'm going to close this so it's removed from view, we'll be reaching out very shortly!

**Pull request closed without merging**
